"""Category Model

Revision ID: ff0a9aac8e68
Revises: f1a580b1c1f4
Create Date: 2023-10-19 00:58:15.762971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ff0a9aac8e68"
down_revision: Union[str, None] = "f1a580b1c1f4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("category_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "products", "categorys", ["category_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "products", type_="foreignkey")
    op.drop_column("products", "category_id")
    # ### end Alembic commands ###
