"""Category Model

Revision ID: 92e1e1684103
Revises: ff0a9aac8e68
Create Date: 2023-10-19 01:03:43.807172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "92e1e1684103"
down_revision: Union[str, None] = "ff0a9aac8e68"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("categorys", sa.Column("parent_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "categorys", "categorys", ["parent_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "categorys", type_="foreignkey")
    op.drop_column("categorys", "parent_id")
    # ### end Alembic commands ###
